"""empty message

Revision ID: 738881aa929e
Revises: 92abb48ab213
Create Date: 2025-06-20 13:07:01.535771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738881aa929e'
down_revision = '92abb48ab213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
